### ISSUE TITLE
Try deploying it on Netlify

### ISSUE THREAD

**Issue by AcceptedDoge** [shaonianruntu/MIL-Experimental-Display-Platform#1]
> [Netlify](https://www.netlify.com/)  is everything you need to build fast, modern websites: continuous deployment, serverless functions, and so much more.

So that people can run it online without configuring and deploying it locally.

**Comment by shaonianruntu** [comment]
> > [Netlify](https://www.netlify.com/)  is everything you need to build fast, modern websites: continuous deployment, serverless functions, and so much more.
> 
> So that people can run it online without configuring and deploying it locally.

Thanks for your suggestion，I really donnot know much about Netlify. But Google told me that it is just a hosting platform for static webpages, a little bit like Github Pages.

But what we do is not a simple static web display project. This  repo is a very early and coarse demo. Duing  to the lack of back-end developers, I built this virtual static front-end for temporary emergency presentation.

Finally, the website will still be placed on a public network server to access and run the back-end AI algorithm through the database. 

The good news is that a complete front-end and back-end AI algorithm display system is under development.
